[phases.setup]
nixPkgs = ["openssl"]

[phases.install]
cmds = [
  "curl -fsSL https://deb.nodesource.com/setup_22.x | bash -",
  "apt-get install -y nodejs",
  "npm ci"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
